- src/client/components/WidgetContainer/widgets/LatestReviews/README.md
We have discussed how to set background styling for widgets. This shows how this could be done for the latest reviews widget.
> Background image and color for widgets

- src/client/components/WidgetContainer/widgets/FactBoxWidget/README.md
This PR contains an initial version of a README for the fact box widget.
> FactBoxWidget example

- src/client/Utils/dateInputPolyfill/date-input-polyfill.scss
- src/client/components/Footer/_footer.scss
- src/client/components/General/Tabs/scss/tabs.component.scss
- src/client/components/General/VisFlereButton/VisFlereButton.component.scss
- src/client/components/Groups/AddContent/scss/addContent.scss
- src/client/components/Groups/General/_colourpicker.component.scss
- src/client/components/Groups/General/_groupform.component.scss
- src/client/components/Groups/Posts/scss/PostView.scss
- src/client/components/Profile/Detail/scss/ProfileDetailContainer.component.scss
- src/client/components/Profile/Edit/profileform.component.scss
- src/client/components/Review/Review.scss
- src/client/components/Review/ReviewList.scss
- src/client/components/Search/SearchResultContainer.scss
- src/client/components/SearchBox/SearchDropDown/searchdropdown.component.scss
- src/client/components/WidgetContainer/widgets/BestRatedWorksWidget/scss/BestRatedWorks.widget.component.scss
- src/client/components/WidgetContainer/widgets/BestRatedWorksWidget/scss/compactWorkElement.component.scss
- src/client/components/WidgetContainer/widgets/FullWidthBannerWidget/scss/FullWidthBannerWidget.component.scss
- src/client/components/WidgetContainer/widgets/LatestReviews/scss/CompactReviewElement.component.scss
- src/client/components/WidgetContainer/widgets/LatestReviews/scss/LatestReviews.widget.component.scss
- src/client/components/Work/BorrowButton/BorrowButton.component.scss
- src/client/scss/settings/colors.scss
+ refactorering af farvekoder til variabler
sd-619
> sd-619: Skift farve på "Vis flere"-knap på søgeresultatside

- .eslintrc
- src/client/components/General/InputField/InputField.component.js
- src/client/components/Profile/Detail/ProfileDetailContainer.component.js
- src/client/components/Profile/Detail/__tests__/ProfileDetailContainer.component.test.js
- src/client/components/Profile/Edit/ProfileLibraryInfo.component.js
- src/client/components/Profile/Edit/__tests__/ProfileLibraryInfo.component.test.js
- src/client/components/Profile/Edit/profileForm.component.js
- src/client/components/Profile/LibraryEdit/LibraryEditContainer.component.js
- src/client/components/SearchBox/SearchContainer.component.js
- src/client/components/SearchBox/SearchDropDown/SearchDropDown.component.js
- src/client/components/SearchBox/SearchDropDown/searchdropdown.component.scss
- src/client/components/Work/BorrowButton/BorrowButton.component.js
sd-579: Brug af piletasterne til at vælge bibliotek under "Rediger profil"
> Brug af piletasterne til at vælge bibliotek under "Rediger profil"

- src/client/components/General/UploadMedia/UploadMedia.component.js
- src/client/components/Groups/AddContent/AddContent.component.js
- src/client/components/Review/Review.component.js
> Move file inputs without name outside form element to counter IE bug.

- src/client/components/SearchBox/SearchFilters/SearchFilters.component.scss
- src/client/components/SearchBox/search-container.scss
- src/client/scss/settings/breakpoints.scss
> fixed issue #60 - squeeze spacing for small-phone (320px)

- selenium/features/SiteSessions.feature
- selenium/features/step_definitions/step_definitions.js
- src/client/components/Navbar/NavbarContainer.component.js
Looks like I messed up with jenkins. Responding to review on #202 here
- using generic step definition
- cleaning displayLogoutWarning
> sd-607 LogoutWarning  ..(take two)

- src/client/components/Groups/Posts/__tests__/PostView.test.js
> sd-621 : Added test for comment burron

- src/client/components/Work/Header/WorkHeader.component.js
- src/client/components/Work/Header/WorkHeader.component.scss
> #220: Billedfeltet øverst på værkside og gruppeside vises forkert

- src/client/components/WidgetContainer/widgets/LatestReviews/LatestReviews.widget.component.js
Update component when cover images are added.
> Issue 211 svi

- src/client/components/Search/SearchResultContainer.component.js
- src/client/components/Work/Detail/WorkDetail.component.scss
- src/client/scss/mixins/result-list.scss
Noget formatering af SearchResultContainer.component.js røg også med ...
> Issue 226 fvs

- src/client/components/Search/SearchResultContainer.component.js
Aner ikke om det har hjulpet for OSX FF
> issue #231: vis flere knap vises med spinner også fra første side

- src/client/Reducers/groupCreate.reducer.js
- src/server/templates/head.pug
Inklussiv en rettelse i head.pug som larmede i IntelliJ
> issue #235 - clear error when picture is uploadet

- src/client/Reducers/groupCreate.reducer.js
- src/client/components/General/Icon/svg/Materialikon-kvadrat-small/other.svg
- src/client/components/General/Icon/svg/Materialikon-kvadrat-small/other_no_border.svg
- src/client/components/Search/MaterialSearchResultList/MaterialSearchResultList.component.js
- src/client/components/Work/Detail/WorkDetail.component.js
- src/client/components/Work/MoreInfo/MoreInfo.component.js
- src/server/templates/head.pug
Igen med tidligere commits filer.
... ignorer rettelser i groupCreate.reducer.js  og head.pug, som ligger i tidligere pull request
> Issue 244 fvs

- src/client/components/Profile/Detail/scss/ProfileDetailContainer.component.scss
- make sure that group button container is relative (so it moves when a search is performed)
- tweak profile header size .
> fixes for profile page

- src/client/components/Profile/Detail/ProfileDetailContainer.component.js
> github #148 : do not show comments on deleted posts in activity feed

- src/client/components/Profile/Detail/ProfileDetailContainer.component.js
- src/server/routes/campaign.routes.js
- src/server/routes/profile.routes.js
- src/server/utils/campaign.util.js
-  fallback to png if svg is not available
-  Introduce getUserContributedCampaigns (to only display badges for campaigns a user has contributed to)
> Fixes for campaign diplomas

- src/server/serviceProvider/transformers/Community/Reviews/getTopReviews.transform.js
- Fix missing cover images in BestRatedWorks
> github #267 use work parser

- src/client/components/Review/Review.component.js
- src/server/routes/review.routes.js
- src/server/serviceProvider/transformers/Community/Reviews/createReview.transform.js
- fix created date bug on reviews
> #273 fix created date bug on reviews

- src/server/utils/campaign.util.js
- throw exception on wrong format on campaigns (waiting for admin to support group id)
- wait for calls to getContributions
> wait for calls to getContributions

- src/client/components/WidgetContainer/widgets/LatestReviews/CompactReviewElement.component.js
line 33 is new. Rest is formatting
> issue #291: format

- src/server/routes/group.routes.js
https://github.com/DBCDK/biblo/commit/e3501549b02af97dbfaea3d6bbe5a19176b22aed#diff-b80e4d76762dd02b6510f89b837953f9R288
> Fixing e350154 - *= -1

- src/client/components/WidgetContainer/widgets/BestRatedWorksWidget/scss/compactWorkElement.component.scss
- src/client/components/WidgetContainer/widgets/BestRatedWorksWidget/scss/compactWorkElementsContainer.component.scss
- src/client/components/WidgetContainer/widgets/LatestGroupPostsWidget/scss/CompactGroupPostElement.component.scss
- src/client/components/WidgetContainer/widgets/PopularGroupsWidget/scss/PopularGroups.widget.component.scss
Mostly corrections for mobile devices
> sd-595: more styling of widgets

- src/client/components/Article/article.scss
- src/client/components/WidgetContainer/WidgetContainer.component.js
- src/client/components/WidgetContainer/widgets/FactBoxWidget/scss/FactBox.widget.component.scss
now two coloumns on section pages
> sd-638: Update styling of factbox widget 

- src/client/components/Review/Review.component.js
- src/client/components/Review/ReviewButton.js
- src/client/components/Work/Detail/WorkDetail.component.js
- src/client/components/Work/WorkContainer.component.js
> #333: Submit button are inactive immediately is had been clicked (+ cleanup)

- src/client/components/Profile/Detail/ProfileDetailContainer.component.js
- src/client/components/Profile/Detail/scss/ProfileDetailContainer.component.scss
Some square images are not square
> Issue 258 1 fvs

- src/client/components/Profile/Detail/ProfileDetailContainer.component.js
> #356: React smider fejl i dev-mode når GroupViewTIle får props.postsSinceLast som ikke er af typen number

- src/client/components/WidgetContainer/__tests__/EditoriallySelectedReviews.widget.test.js
- src/client/components/WidgetContainer/widgetContainer.scss
- src/client/components/WidgetContainer/widgets/BestRatedWorksWidget/compactWorkElement.component.js
- src/client/components/WidgetContainer/widgets/BestRatedWorksWidget/scss/compactWorkElement.component.scss
- src/client/components/WidgetContainer/widgets/BestRatedWorksWidget/scss/compactWorkElementsContainer.component.scss
- src/client/components/WidgetContainer/widgets/EditoriallySelectedReviewsWidget/EditoriallySelectedReviews.widget.component.js
- src/client/components/WidgetContainer/widgets/EditoriallySelectedReviewsWidget/scss/EditoriallySelectedReviews.widget.component.scss
- src/client/components/WidgetContainer/widgets/LatestGroupPostsWidget/scss/LatestGroupPosts.widget.component.scss
- src/client/components/WidgetContainer/widgets/LatestReviews/scss/CompactReviewElement.component.scss
- src/client/components/WidgetContainer/widgets/LatestReviews/scss/LatestReviews.widget.component.scss
- src/client/components/WidgetContainer/widgets/PopularGroupsWidget/scss/PopularGroups.widget.component.scss
- src/client/scss/extends/widgets.scss
- src/client/scss/mixins/content-grid.scss
> Small styling fixes for multiple widgets

- jsonpage.json
- package.json
- src/client/components/WidgetContainer/PaginationContainer.component.js
- src/client/components/WidgetContainer/__tests__/PopularGroups.widget.test.js
- src/client/components/WidgetContainer/scss/PaginationContainer.component.scss
- src/client/components/WidgetContainer/widgets/BestRatedWorksWidget/BestRatedWorks.widget.component.js
- src/client/components/WidgetContainer/widgets/BestRatedWorksWidget/scss/BestRatedWorks.widget.component.scss
- src/client/components/WidgetContainer/widgets/BestRatedWorksWidget/scss/compactWorkElement.component.scss
- src/client/components/WidgetContainer/widgets/LatestPostsWidget/LatestPosts.widget.component.js
- src/client/components/WidgetContainer/widgets/LatestReviews/LatestReviews.widget.component.js
- src/client/components/WidgetContainer/widgets/PopularGroupsWidget/PopularGroups.widget.component.js
- src/client/components/WidgetContainer/widgets/PopularGroupsWidget/scss/PopularGroups.widget.component.scss
- src/server/serviceProvider/transformers/Community/Reviews/getTopReviews.transform.js
Also update community client, implement generic loading spinner for pagination component.
> sd-700: implement pagination on BestRatedWorksWidget.

- package.json
- selenium/__mocks__/LegoBatmanMovie.mock.js
- selenium/__mocks__/LegoIndianaJones.mock.js
- selenium/__mocks__/bestRatedWorksWidget.mock.js
- selenium/__mocks__/editoriallySelectedMaterialsWidget.mock.js
- selenium/__mocks__/editoriallySelectedReviewsWidget.mock.js
- selenium/__mocks__/krigerkattene.mock.js
- selenium/__mocks__/peterpedal.mock.js
> change openplatform url in mocks + fix failing test

- src/client/components/Navbar/NavBarProfileImage.component.js
Der er et problem med et par ekstra spaces i denne fil (trods den ikke er rørt i lang tid), jeg tillader mig at presse den igennem med det samme.
> lint problem

- package.json
Closes #451
https://greenkeeper.io/
> chore(package): update chromedriver to version 2.25.3

- src/server/serviceProvider/transformers/OpenPlatform/work.transform.js
Also generally for work requests
> Allow more than 20 works in EditoriallySelectedMaterialsWidget

- package.json
Closes #494
https://greenkeeper.io/
> fix(package): update redux-thunk to version 2.2.0

- package.json
Closes #486
https://greenkeeper.io/
> chore(package): update karma-webpack to version 2.0.2

- src/server/serviceProvider/parsers/work.parser.js
> check if property exists on response object on multivolume

- src/client/components/Groups/General/GroupDisplayUtils.js
- src/client/components/Review/Review.component.js
- src/client/components/Review/ReviewList.js
- src/client/components/Work/Detail/WorkDetail.component.js
> Autoplay af video i anmeldelse

- src/client/components/Profile/Detail/ProfileDetailContainer.component.js
> fix scaling of campaign svg's in profile view

- src/server/serviceProvider/transformers/Community/Groups/getPosts.transform.js
- src/server/serviceProvider/transformers/Community/Reviews/getCampaignReviews.transform.js
> disable caching of campaign diploma

- src/client/Actions/review.actions.js
- src/client/components/ReviewExplorer/ReviewExplorerItem.js
- src/client/components/ReviewExplorer/ReviewExplorerNavigation.js
- src/client/components/ReviewExplorer/scss/ReviewExplorerItem.scss
styling + filtrering af spil og film
> Anmeldelses-oversigt

- .gitignore
- src/client/components/WidgetContainer/__tests__/EditoriallySelectedReviews.widget.test.js
- src/client/components/WidgetContainer/widgets/EditoriallySelectedMaterialsWidget/EditoriallySelectedMaterials.widget.component.js
- src/client/components/WidgetContainer/widgets/EditoriallySelectedReviewsWidget/EditoriallySelectedReviews.widget.component.js
> Fjern "Vis flere"-knap

- package.json
- src/client/Utils/__tests__/sanitizeHtml.util.test.js
- src/client/Utils/sanitizeHtml.util.js
- src/client/components/CampaignCertificate/CampaignCertificate.component.js
- src/client/components/ContentPage/ContentPage.component.js
- src/client/components/Groups/Comments/CommentView.component.js
- src/client/components/Groups/Posts/PostView.component.js
- src/client/components/Groups/View/GroupViewContainer.component.js
- src/client/components/Groups/View/GroupViewTile.component.js
- src/client/components/Profile/Detail/ProfileDetailContainer.component.js
- src/client/components/Profile/Detail/ReviewRow.component.js
- src/client/components/Profile/Messages/MessageRow.component.js
- src/client/components/Review/Review.component.js
- src/client/components/Review/ReviewList.js
- src/client/components/WidgetContainer/widgets/ContentPageTextWidget/ContentPageText.widget.component.js
- src/client/components/WidgetContainer/widgets/EditoriallySelectedReviewsWidget/EditoriallySelectedReviews.widget.component.js
- src/client/components/WidgetContainer/widgets/FactBoxWidget/FactBox.widget.component.js
- src/client/components/WidgetContainer/widgets/LatestGroupPostsWidget/CompactGroupPostElement.component.js
- src/client/components/WidgetContainer/widgets/LatestReviews/CompactReviewElement.component.js
- src/client/components/WidgetContainer/widgets/PopularGroupsWidget/PopularGroups.widget.component.js
> Clean up af tags etc. i brugernavn

- src/client/components/Search/MaterialSearchResultList/MaterialSearchResultList.component.js
- src/server/serviceProvider/parsers/__tests__/work.parser.test.js
- src/server/serviceProvider/parsers/work.parser.js
> 2 x https:

- package.json
- selenium/features/groups/GroupMembersBox.feature
- src/client/components/Profile/Edit/DisplayNameField.component.js
- src/client/components/Profile/Edit/profileForm.component.js
- src/server/serviceProvider/parsers/__tests__/profile.parser.test.js
- src/server/serviceProvider/parsers/mocks/profile.parser.mock.js
- src/server/serviceProvider/parsers/profile.parser.js
- src/server/utils/__tests__/sanitizeHtml.util.test.js
- src/server/utils/serverSideSanitizeHtml.util.js
- tests.server.webpack.js
- webpack.test.config.js
> Sanitize input

- src/client/components/Search/GroupSearchResultList/GroupSearchResultList.component.js
- src/client/components/Search/MaterialSearchResultList/MaterialSearchResultList.component.js
- src/client/components/SearchBox/SearchFilters/SearchFilters.component.js
- src/client/components/SearchBox/SearchFilters/SearchFilters.component.scss
- src/client/scss/mixins/result-list.scss
> Padding + SVG issues

- src/client/components/WidgetContainer/widgets/EditoriallySelectedReviewsWidget/scss/EditoriallySelectedReviews.widget.component.scss
> IE text overflow

- src/server/routes/main.routes.js
#729
200 hvis alt er OK ellers 503 (Service Unavailable)
> /howru status

- selenium/__mocks__/LegoBatmanMovie.mock.js
- selenium/__mocks__/LegoIndianaJones.mock.js
- selenium/__mocks__/fangerneDragsholm.mock.js
- selenium/__mocks__/krigerkattene.mock.js
- selenium/__mocks__/peterpedal.mock.js
- selenium/__mocks__/tintin-moreseries.mock.js
- selenium/__mocks__/tintin.mock.js
- src/server/routes/work.routes.js
> Review count bugfix

- src/client/components/Work/Header/WorkHeader.component.js
- src/client/components/Work/Header/WorkHeader.component.scss
#624
Placerer forside billedet med bunden som fixpunkt.
> Dynamic adjustment of cover image

- src/server/utils/campaign.util.js
> Bad formatting of error message

- src/client/components/WidgetContainer/widgets/LatestReviews/scss/CompactReviewElement.component.scss
> Fixes placement of stars in review widget

- src/client/components/ContentPage/contentPage.scss
> Reduced distance between elements on article pages

- src/client/Utils/userHasSelectedFavouriteLibrary.util.js
- src/client/components/Review/__tests__/ReviewButton.test.js
> Do not require userId and pin to be set to add review

- src/client/components/Work/MultiVolumeDisplay/MultiVolumeDisplay.component.js
- src/client/components/Work/MultiVolumeDisplay/__tests__/MultiVolumeDisplay.component.test.js
- src/client/components/Work/MultiVolumeDisplay/__tests__/__snapshots__/MultiVolumeDisplay.component.test.js.snap
- src/client/components/Work/MultiVolumeDisplay/__tests__/krigerkattene.mock.js
> Only render one of each bind X

- package.json
- src/client/components/Profile/Edit/ProfileLibraryInfo.component.js
- src/client/components/Profile/Edit/ProfileLibraryInfoModalContainer.component.js
og ikke låner-id og pin-kode
#774
> Ved opret anmeldelse med profil uden bibliotek, skal der kun spørges efter bibliotek

- src/client/components/Profile/Edit/DisplayNameField.component.js
- src/client/components/Profile/Edit/ProfileLibraryInfo.component.js
- src/client/components/Profile/Edit/profileForm.component.js
- src/client/components/Profile/Edit/profileform.component.scss
> 781 tekst rettelser profil redigering

- .gitignore
- src/client/components/Groups/Posts/PostView.component.js
> count of comments to load in groups fixed

- .gitignore
- package-lock.json
- src/client/components/Groups/View/GroupViewTile.component.js
- src/client/components/Groups/View/scss/group-tile.scss
> group icon size fixed

- src/server/serviceProvider/transformers/Community/Profile/getFullProfile.transform.js
- src/server/serviceProvider/transformers/Community/Profile/updateProfile.transform.js
- src/server/utils/crypto.util.js
> Encrypt favourite library

- src/client/Actions/group.actions.js
- src/server/serviceProvider/clients/community.client.js
- src/server/serviceProvider/transformers/Community/Groups/deletePost.transform.js
- src/server/serviceProvider/transformers/Community/Reviews/deleteReview.transform.js
> Delete content instead of deleted mark

- src/server/serviceProvider/clients/amazon.client.js
- src/server/serviceProvider/transformers/Community/Profile/deleteProfile.transform.js
> Delete user content from AWS

- src/client/components/WidgetContainer/widgets/BestRatedWorksWidget/BestRatedWorks.widget.component.js
- src/client/components/WidgetContainer/widgets/BestRatedWorksWidget/scss/BestRatedWorks.widget.component.scss
- src/client/components/WidgetContainer/widgets/BestRatedWorksWidget/scss/compactWorkElement.component.scss
- src/client/components/WidgetContainer/widgets/BestRatedWorksWidget/scss/compactWorkElementsContainer.component.scss
> 795 best rated books autoload

- package-lock.json
- package.json
- src/server/serviceProvider/clients/community.client.js
> moderator should follow group

- src/server/serviceProvider/transformers/Community/Profile/updateProfile.transform.js
> Check if favoritelibrary is set on update

- src/client/App.js
> 798 update profile picture

- src/server/serviceProvider/transformers/Community/Profile/getFullProfile.transform.js
> if favourite library is a string, try to json parse

- src/client/components/Groups/AddContent/AddContent.component.js
> group state double update fixed

- src/client/components/WidgetContainer/widgets/BestRatedWorksWidget/scss/compactWorkElement.component.scss
Solves a styling issue in bestRatedWorks-widget works titles
> Best rated works multiple line style issue

- src/client/components/Review/Review.component.js
> 819 autofocus on inputfield in new review

- src/client/components/Profile/Delete/ProfileDeleteContainer.component.js
- src/client/components/Profile/Delete/ProfileDeleteModal.component.js
- src/client/components/Profile/Delete/ProfileDeleteStyling.scss
- src/client/components/Profile/Delete/__tests__/ProfileDeleteModal.component.test.js
- src/client/components/Profile/Delete/__tests__/__snapshots__/ProfileDeleteModal.component.test.js.snap
> Add ekstra step when deleting profile

- src/client/Reducers/profile.reducer.js
- src/server/routes/profile.routes.js
> 798 change profile picture

- src/client/App.js
- src/client/Reducers/work.reducer.js
- src/client/components/Work/BorrowButton/BorrowButton.component.js
- src/client/components/Work/SeriesDisplay/SeriesDisplay.component.js
solves #832 and also solves issues with availability check
> 832 fix bug in series title

- src/client/components/Profile/Messages/MessagesContainer.component.js
> double notification issue frontend fix

- src/client/components/ContentPage/ContentPage.component.js
- src/client/components/Profile/Messages/MessagesContainer.component.js
- src/server/serviceProvider/parsers/userMessage.parser.js
> double notifications backend fix

- src/server/serviceProvider/parsers/userMessage.parser.js
- src/server/serviceProvider/transformers/UserMessages/getUserMessages.transform.js
> delete double messages using DeleteMessageTransform

- src/client/components/Profile/Edit/DisplayNameField.component.js
- src/client/components/Profile/Edit/profileForm.component.js
> modal issue fixed

- src/server/serviceProvider/parsers/work.parser.js
> adjust regex to include different worktypes containing "bind"

- src/server/routes/work.routes.js
> Fetch reviews for all pids in volume

- src/server/serviceProvider/transformers/Community/Reviews/getReview.transform.js
part of https://github.com/DBCDK/dbc-community-service/issues/109
> Set default limit to avoid fetching all reviews

- src/server/serviceProvider/transformers/Community/Groups/getComments.transform.js
- src/server/serviceProvider/transformers/Community/Groups/getGroup.transform.js
- src/server/serviceProvider/transformers/Community/Groups/getGroupId.transform.js
- src/server/serviceProvider/transformers/Community/Groups/getGroupMembers.transform.js
- src/server/serviceProvider/transformers/Community/Groups/getLatestPosts.transform.js
- src/server/serviceProvider/transformers/Community/Groups/getPosts.transform.js
- src/server/serviceProvider/transformers/Community/Groups/getSingleComment.transform.js
- src/server/serviceProvider/transformers/Community/Groups/getSinglePost.transform.js
For at forhindre evt requests til community service der har id undefined, og dermed vil forsøge at hente alt
> check id is valid in a bunch of transformers

- package-lock.json
- package.json
- src/app.js
- src/client/Actions/quiz.actions.js
- src/client/Constants/action.constants.js
- src/client/Reducers/quiz.reducer.js
- src/client/Reducers/root.reducer.js
- src/client/components/WidgetContainer/widgets/QuizWidget/ExternalQuizWrapper.component.js
- src/client/components/WidgetContainer/widgets/QuizWidget/Quiz.widget.component.js
- src/client/components/WidgetContainer/widgets/QuizWidget/scss/Quiz.widget.component.scss
- src/client/components/WidgetContainer/widgets/index.js
- src/server/routes/api.routes.js
- src/server/routes/main.routes.js
- src/server/templates/page.pug
#862 
#863 
De tilføjede session-api-endpoints tilgængelige for klienten, lægger objekter under session.stored - så man ikke kan komme til at lave rod i den øvrige del af session.
Virker ikke til at jeg havde fået kørt prettier på det hele :/
selenium tests laver jeg først når quiz-resultat kan gemmes til community service
> 862+863 quiz widget 

- src/client/Actions/quiz.actions.js
- src/client/components/WidgetContainer/widgets/QuizWidget/Quiz.widget.component.js
> send library stats to quiz, some error handling

- src/client/Actions/quiz.actions.js
- src/client/components/Profile/Detail/ProfileDetailContainer.component.js
- src/client/components/Profile/Detail/__tests__/ProfileDetailContainer.component.test.js
- src/client/components/Profile/Detail/scss/ProfileDetailContainer.component.scss
- src/server/serviceProvider/clients/community.client.js
- src/server/serviceProvider/transformers/Community/Quiz/getResults.transform.js
> 885 quiz badges kfu

- src/app.js
solves [[BIBLO-1234]](https://dbcjira.atlassian.net/browse/BIBLO-1234)
> Redirect to edit profile page if user is logged in without profile

- src/app.js
- src/server/middlewares/auth.middleware.js
Part for [[BIBLO-1234]](https://dbcjira.atlassian.net/browse/BIBLO-1234)
> Prevent redirect loop on create profile

- src/server/routes/content.routes.js
solves [[BIBLO-1236]](https://dbcjira.atlassian.net/browse/BIBLO-1236)
> Use path instead of full url

- junit.xml
- src/app.js
- src/client/Actions/profile.actions.js
- src/client/App.js
- src/client/components/Profile/Messages/MessageRow.component.js
- src/server/queues/checkForNewAdminMessages.queue.js
- src/server/routes/api.routes.js
- src/server/serviceProvider/clients/community.client.js
- src/server/serviceProvider/handlers/ChangeStream.handlers.js
- src/server/serviceProvider/parsers/userMessage.parser.js
- src/server/serviceProvider/transformers/Community/Profile/getAdminMessages.transform.js
> Biblo-1230 admin messages

- src/client/components/ModeratorMessageModal/ModeratorMessageModal.component.js
- src/server/serviceProvider/parsers/userMessage.parser.js
> delete duplicated admin messages

- src/server/serviceProvider/parsers/userMessage.parser.js
BIBLO-1230-admin-messages userMessage parser modified
> BIBLO-1230-admin-messages userMessage parser modified

- src/server/routes/main.routes.js
- src/server/templates/ddbmarker.pug
- src/server/templates/head.pug
> include 'DDB fælles markør' on Biblo frontpage

- junit.xml
- src/client/components/Layout/PageLayout.component.js
- src/server/queues/UserMessages.queue.js
- src/server/serviceProvider/clients/amazon.client.js
> Revert "removed-dynamo-requests"

- src/client/components/Layout/PageLayout.component.js
> message request-interval set to 5 min
